apiVersion: batch/v1
kind: Job
metadata:
  name: <serviceName>-migrate
spec:
  template:
    metadata:
      labels:
        app: <serviceName>-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: <serviceName>-migrate
          image: <REGISTRY + IMAGE + TAG>
          args: ["-env", "dev", "-service", "<serviceName>-migrate", "-path", "/migration", "up"]
