apiVersion: batch/v1
kind: Job
metadata:
  name: goal-migrate
spec:
  template:
    metadata:
      labels:
        app: goal-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: goal-migrate
          image: 301771908274.dkr.ecr.us-east-2.amazonaws.com/goal-migrate:c9262c736205006b15f855a6468c94ca3fb28889
          args: ["-env", "dev", "-service", "goal-migrate", "-path", "/migration", "up"]
