kind: PersistentVolume
apiVersion: v1
metadata:
  name: goal-db
  labels:
    type: local
    app: goal-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/tmp/k8s-goal-db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: goal-db-pv-claim
  labels:
    app: goal-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-db
spec:
  selector:
    matchLabels:
      app: goal-db
  replicas: 1
  template:
    metadata:
      labels:
        app: goal-db
    spec:
      containers:
        - name: goal-db
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: goal
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: goal-db-vol
      volumes:
        - name: goal-db-vol
          persistentVolumeClaim:
            claimName: goal-db-pv-claim
