apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal
spec:
  template:
    metadata:
      labels:
        app: goal
    spec:
      containers:
        - name: goal
          image: goal:latest
          ports:

          # don't try to pull the image since it was built locally
          imagePullPolicy: Never
          env:
            - name: HMD_ENVIRONMENT
              value: "local"
          envFrom:
            - secretRef:
                name: aws-auth
