apiVersion: v1
kind: Service
metadata:
   name: goal
spec:
   selector:
      app: goal
   ports:
      - name: http
        port: 8080
        # UNCOMMENT AND SET THE LINE BELOW TO FORWARD A STATIC HOST PORT
      #   nodePort: 30001
