apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: <serviceName>
spec:
  selector:
    matchLabels:
      app: <serviceName>
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: <serviceName>
    spec:
      containers:
        - name: <serviceName>
          image: <serviceName>-image
          ports:
            - containerPort: 8080
          env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: AWS_REGION
              value: "us-east-2"
            - name: PGHOST
              value: "<serviceName>-db"
            - name: PGPORT
              value: "5432"
