apiVersion: batch/v1
kind: Job
metadata:
  name: goal-migrate
spec:
  template:
    metadata:
      labels:
        app: goal-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: goal-migrate
          image: goal-migrate:latest
          args: ["-url", "postgres://postgres:postgres@goal-db/goal?sslmode=disable", "-path", "/migration", "up"]
          imagePullPolicy: Never
