apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: goal
    spec:
      containers:
        - name: goal
          image: <REGISTRY + IMAGE + TAG>
          env:
            - name: HMD_ENVIRONMENT
              value: "dev"
