apiVersion: v1
kind: Service
metadata:
   name: goal
spec:
   selector:
      app: goal
   ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
