apiVersion: v1
kind: Service
metadata:
   name: <serviceName>
   annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /<serviceName>/v1/test/ping
spec:
   selector:
      app: <serviceName>
   ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8080
